### ISSUE TITLE
deal w/ persistent storage issues on EKS

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#132]
Probably need to set volumeBindingMode if/when EKS picks up support for K8s 1.12. It's unclear at the moment whether that will be entirely sufficient to make persistent storage work on EKS... maybe it will!

The issue: https://github.com/kubernetes/kubernetes/issues/34583

The solution: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

**Comment by joel-bluedata** [comment]
Actually I misunderstood volumeBindingMode. That's a property on the StorageClass, not on the PVC. So if Amazon sets this, then things should "just work" for us when using 1.12 without any KD changes.

**Comment by joel-bluedata** [comment]
Might get 1.12 on EKS soon: https://github.com/aws/containers-roadmap/issues/24

**Comment by pawelprazak** [comment]
The current (`v1.12.6-eks-d69f1b`) default storage class does not configure this:
```
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    name: gp2
  parameters:
    fsType: ext4
    type: gp2
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
```
