### ISSUE TITLE
config_meta validation

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#27]
This needs to be a "dictionary" (object with arbitrary property names) of string values.

In K8s 1.11 and later, we should be able to do this through schema validation i.e.
```yaml
config_meta:
  type: object
  additionalProperties:
    type: string
```

However for supporting earlier K8s versions I guess we need to do it in dynamic validation instead. Or we could move to modeling it as an array of sub-objects with explicit key/value properties.
