### ISSUE TITLE
kubedirector still ignoring roles with cardinality 0+ while creating cluster.

### ISSUE THREAD

**Issue by omhpe** [bluek8s/kubedirector#345]
The optional roles having cardinality of 0+ are still not getting created inspite of mentioning them in cluster yaml.

More details in the below comment link of the original issue that was reported.

https://github.com/bluek8s/kubedirector/issues/317#issuecomment-634470921

**Comment by joel-bluedata** [comment]
The title of this issue does not sound similar to what was observed in issue #317, so it's not clear to me what symptom you're reporting.

But note that when you have a role config in your kdcluster, if you do not specify a number of members then the valid minimum will be assumed. If the minimum is 0, then you will have 0 members in that role unless you specify otherwise. So if you want more than the minimum, specify that with the "members" attribute, e.g.
```
  - id: gateway
    members: 2
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    storage:
      size: "50Gi"
```

Looking through our example kdclusters I see some commented-out roles that don't provide a members attribute; likely that's a source of confusion that we need to fix, if those are 0+ cardinality roles.

If that's not the problem you're having though, then please provide as much detail as possible about:
* what build of KD you are using, on what version of K8s
* the content of the kdapp that you are using
* what the observed issue is and what steps you can take to reproduce it.
