### ISSUE TITLE
Question: Is it possible to add CSI persistent volumes to a KD managed POD?

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#411]
In this use case, the user does not want to use dataTap to access data but instead wishes to mount volumes instead.

Is this possible with KD?  If so, how?

**Comment by snowch** [comment]
If it isn't supported - no worries.  I can add this as a feature request.

**Comment by snowch** [comment]
@swamibluedata are CSI PV mounts possible?

**Comment by joel-bluedata** [comment]
Reading this as : mounting PVs that have a lifecycle independent of the pods, and probably sharing the PVs among pods as well.

Yep this would be a feature request. Probably an interesting bit of discussion... throwing the door completely open to arbitrary kdcluster-specified mounts would be easy but perhaps not the right approach.

**Comment by swamibluedata** [comment]
Assuming that user has created a pv and pvc, proposing a following change to KDCluster CRD at individual role level

                  volumeProjections:
                    type: object
                    nullable: true
                    required: [volumeName, mountPath]
                    properties:
                      volumeName:
                        type: string
                      mountPath:
                        type: string
                      readOnly:
                        type: boolean

**Comment by swamibluedata** [comment]
Final Cluster CRD change
```
volumeProjections:
  type: array
  items:
    type: object
    nullable: true
    required: [volumeName, mountPath]
    properties:
      volumeName:
        type: string
      mountPath:
        type: string
      readOnly:
        type: boolean
```

Validation changes - Validate every volume to make sure PVC exists in the KD Cluster's namespace. We should also validate mountPath to make sure it doesn't conflict with persistDirs
Statefulset Preparation - Create projected volumes in statefulset either with readonly or readwrite 

One issue i see is that if PVC was created with ReadWriteOnce (Or the new ReadWriteOncePod) and multiple pods are mounting the volume, pod creation can go into pending. 

Since we don't know the intent of the user, we can't do any validation. @joel-bluedata
