### ISSUE TITLE
Question: how to use the cr-cluster-spark245.yaml image?

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#413]
The `cr-cluster-spark245.yaml` contains a config map and secret but both are commented out - I've looked at the doc `spark245-with-jupyterhub-readme.md` but it doesn't really describe how to use the image.

**Comment by riteshja** [comment]
Hi @snowch 

The `cr-cluster-spark245.yaml` contains 2 secrets and 1 configmap. The `jupyterhub` configmap and `jupyterhubsecret` secret are used to provide LDAP server authentication details to enable LDAP auth for jupyterhub. So, if you want to enble ldap auth for jupyterhub, uncomment `jupyterhub` configmap and `jupyterhubsecret` secret, and provide corresponding values for the fields of the configmap and the secret. Most of the fields are similar to what we provide on the "Authentication" page of ECP UI. Note that you will have to uncomment the connections block in the kubedirectorcluster section as well to activate the `jupyterhub` configmap and `jupyterhubsecret` secret.

Here would be a sample cluster yaml for enabling LDAP Authentication:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub
  labels:
    kubedirector.hpe.com/cmType : jupyterhub_ldap_config
  data:
     jupyterhub_server_address: "16.143.20.82"
     jupyterhub_server_port: "389"
     jupyterhub_lookup_dn: "True"
     jupyterhub_user_search_base: "dc=mip,dc=storage,dc=hpecorp,dc=net"
     jupyterhub_user_attribute: "cn"
     jupyterhub_bind_user_dn: "cn=admin,dc=mip,dc=storage,dc=hpecorp,dc=net"
  
apiVersion: v1
kind: Secret
metadata:
   name: jupyterhubsecret
   labels:
     kubedirector.hpe.com/secretType : jupyterhub_ldap_secret
   type: Opaque
   data:
     #password is encoded as a base64  string
     jupyterhub_bind_user_password: YWRtaW4xMjMK    

apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "spark245-instance"
spec:
  app: spark245
  connections:
     configmaps:
      - jupyterhub
     secrets:
      - jupyterhubsecret
  roles:
  - id: spark-master
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: livy-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: spark-worker
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: notebook-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"`
```

 If you don't want LDAP auth, and want to login to jupyterhub using a custom username and password, you will have to uncomment  `notebookusersecret` secret. 

Here's what a  yaml for custom username:password  snowch:snowch would look like. Note the username and password would have to be base64 encoded.

```
apiVersion: v1
kind: Secret
metadata:
  name: notebookusersecret
  labels:
    kubedirector.hpe.com/secretType : notebookusersecret
  type: Opaque
 data:
    notebook_username: YWRtaW4K
    notebook_password: YWRtaW4xMjMK

apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "spark245-instance"
spec:
  app: spark245
  connections:
     secrets:
     - notebookusersecret
  roles:
  - id: spark-master
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: livy-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: spark-worker
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: notebook-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
```
If you dont uncomment any of the secrets and configmaps in the yaml and submit it as-is, jupyterhub comes up with default username:password as `admin:admin123`.  

We will put this info in the doc. Thanks for pointing out.
