### ISSUE TITLE
new v1 schemas don't preserve pod/service labels/annotations

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#611]
So, the passthrough labels and annotations have always been of this form:
```yaml
                    podAnnotations:
                      nullable: true
                      type: object
```
... but in the v1 schema any of the contained labels/annotations will be dropped. We need to change them to read as:
```yaml
                    podAnnotations:
                      nullable: true
                      type: object
                      additionalProperties:
                        type: string
```

(and do a quick survey for any similar issues)
